# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1482, 872)
        MainWindow.setMinimumSize(QtCore.QSize(1482, 872))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 641, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ticketChooser = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ticketChooser.setContentsMargins(0, 0, 0, 0)
        self.ticketChooser.setObjectName("ticketChooser")
        self.timeFrom = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeFrom.setFont(font)
        self.timeFrom.setKeyboardTracking(False)
        self.timeFrom.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeFrom.setCalendarPopup(False)
        self.timeFrom.setObjectName("timeFrom")
        self.ticketChooser.addWidget(self.timeFrom, 3, 1, 1, 1)
        self.eventDate = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventDate.setFont(font)
        self.eventDate.setText("")
        self.eventDate.setObjectName("eventDate")
        self.ticketChooser.addWidget(self.eventDate, 8, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.ticketChooser.addWidget(self.label_6, 11, 0, 1, 1)
        self.dateFrom = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateFrom.setFont(font)
        self.dateFrom.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setCurrentSectionIndex(0)
        self.dateFrom.setObjectName("dateFrom")
        self.ticketChooser.addWidget(self.dateFrom, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ticketChooser.addWidget(self.label_7, 12, 0, 1, 1)
        self.soldTicketsCount = QtWidgets.QLabel(self.gridLayoutWidget)
        self.soldTicketsCount.setText("")
        self.soldTicketsCount.setObjectName("soldTicketsCount")
        self.ticketChooser.addWidget(self.soldTicketsCount, 12, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ticketChooser.addWidget(self.label, 7, 0, 1, 1)
        self.eventSiteChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventSiteChoice.setFont(font)
        self.eventSiteChoice.setObjectName("eventSiteChoice")
        self.ticketChooser.addWidget(self.eventSiteChoice, 5, 1, 1, 2)
        self.dateTo = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateTo.setFont(font)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.ticketChooser.addWidget(self.dateTo, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ticketChooser.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.ticketChooser.addWidget(self.label_18, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ticketChooser.addWidget(self.label_10, 2, 0, 1, 1)
        self.availableTicketsCount = QtWidgets.QLabel(self.gridLayoutWidget)
        self.availableTicketsCount.setText("")
        self.availableTicketsCount.setObjectName("availableTicketsCount")
        self.ticketChooser.addWidget(self.availableTicketsCount, 11, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.ticketChooser.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.ticketChooser.addWidget(self.label_9, 0, 0, 1, 1)
        self.timeTo = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeTo.setFont(font)
        self.timeTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 0)))
        self.timeTo.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeTo.setObjectName("timeTo")
        self.ticketChooser.addWidget(self.timeTo, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ticketChooser.addWidget(self.label_3, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ticketChooser.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.ticketChooser.addWidget(self.label_19, 9, 0, 1, 1)
        self.eventChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventChoice.setFont(font)
        self.eventChoice.setObjectName("eventChoice")
        self.ticketChooser.addWidget(self.eventChoice, 7, 1, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.ticketChooser.addWidget(self.label_17, 4, 0, 1, 1)
        self.allTicketsCount = QtWidgets.QLabel(self.gridLayoutWidget)
        self.allTicketsCount.setText("")
        self.allTicketsCount.setObjectName("allTicketsCount")
        self.ticketChooser.addWidget(self.allTicketsCount, 10, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.ticketChooser.addWidget(self.label_14, 6, 0, 1, 1)
        self.eventSiteTypeChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventSiteTypeChoice.setFont(font)
        self.eventSiteTypeChoice.setObjectName("eventSiteTypeChoice")
        self.ticketChooser.addWidget(self.eventSiteTypeChoice, 4, 1, 1, 2)
        self.eventTime = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventTime.setFont(font)
        self.eventTime.setText("")
        self.eventTime.setObjectName("eventTime")
        self.ticketChooser.addWidget(self.eventTime, 9, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ticketChooser.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.ticketChooser.addWidget(self.label_16, 0, 2, 1, 1)
        self.eventTypeChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eventTypeChoice.setFont(font)
        self.eventTypeChoice.setObjectName("eventTypeChoice")
        self.ticketChooser.addWidget(self.eventTypeChoice, 6, 1, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(700, 20, 761, 831))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.choiceTables = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.choiceTables.setContentsMargins(0, 0, 0, 0)
        self.choiceTables.setObjectName("choiceTables")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.choiceTables.addWidget(self.label_4, 0, 0, 1, 1)
        self.choiceTable = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.choiceTable.setObjectName("choiceTable")
        self.choiceTables.addWidget(self.choiceTable, 0, 1, 1, 1)
        self.viewTable = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.viewTable.setObjectName("viewTable")
        self.viewTable.setColumnCount(0)
        self.viewTable.setRowCount(0)
        self.choiceTables.addWidget(self.viewTable, 1, 0, 1, 2)
        self.addTool = QtWidgets.QTabWidget(self.centralwidget)
        self.addTool.setGeometry(QtCore.QRect(20, 530, 641, 321))
        self.addTool.setObjectName("addTool")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.addEventSite = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.addEventSite.setContentsMargins(0, 0, 0, 0)
        self.addEventSite.setObjectName("addEventSite")
        self.eventSiteName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eventSiteName.setEnabled(True)
        self.eventSiteName.setFrame(True)
        self.eventSiteName.setDragEnabled(False)
        self.eventSiteName.setReadOnly(False)
        self.eventSiteName.setClearButtonEnabled(False)
        self.eventSiteName.setObjectName("eventSiteName")
        self.addEventSite.addWidget(self.eventSiteName)
        self.eventSiteType = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eventSiteType.setObjectName("eventSiteType")
        self.addEventSite.addWidget(self.eventSiteType)
        self.addEventSiteButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addEventSiteButton.setObjectName("addEventSiteButton")
        self.addEventSite.addWidget(self.addEventSiteButton)
        self.addTool.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 631, 271))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.addEvent = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.addEvent.setContentsMargins(0, 0, 0, 0)
        self.addEvent.setObjectName("addEvent")
        self.eventSiteChoiceTool = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.eventSiteChoiceTool.setObjectName("eventSiteChoiceTool")
        self.addEvent.addWidget(self.eventSiteChoiceTool, 0, 2, 1, 2)
        self.addEventButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.addEventButton.setObjectName("addEventButton")
        self.addEvent.addWidget(self.addEventButton, 5, 0, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.addEvent.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.addEvent.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.addEvent.addWidget(self.label_8, 4, 0, 1, 1)
        self.rowsCount = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.rowsCount.setMinimum(1)
        self.rowsCount.setMaximum(1000)
        self.rowsCount.setObjectName("rowsCount")
        self.addEvent.addWidget(self.rowsCount, 4, 1, 1, 1)
        self.placesCount = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.placesCount.setMinimum(1)
        self.placesCount.setMaximum(1000)
        self.placesCount.setObjectName("placesCount")
        self.addEvent.addWidget(self.placesCount, 4, 3, 1, 1)
        self.eventName = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.eventName.setObjectName("eventName")
        self.addEvent.addWidget(self.eventName, 1, 0, 1, 4)
        self.eventType = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.eventType.setObjectName("eventType")
        self.addEvent.addWidget(self.eventType, 2, 0, 1, 4)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.addEvent.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.addEvent.addWidget(self.label_21, 3, 2, 1, 1)
        self.eventDateChoice = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.eventDateChoice.setCalendarPopup(True)
        self.eventDateChoice.setObjectName("eventDateChoice")
        self.addEvent.addWidget(self.eventDateChoice, 3, 1, 1, 1)
        self.eventTimeChoice = QtWidgets.QTimeEdit(self.gridLayoutWidget_3)
        self.eventTimeChoice.setObjectName("eventTimeChoice")
        self.addEvent.addWidget(self.eventTimeChoice, 3, 3, 1, 1)
        self.addTool.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.addTool.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Билетное Агенство \"Кузница\""))
        self.label_6.setText(_translate("MainWindow", "Доступно к покупке"))
        self.label_7.setText(_translate("MainWindow", "Продано"))
        self.label.setText(_translate("MainWindow", "Выберите мероприятие"))
        self.label_12.setText(_translate("MainWindow", "По"))
        self.label_18.setText(_translate("MainWindow", "Дата мероприятия"))
        self.label_10.setText(_translate("MainWindow", "Выберите время"))
        self.label_15.setText(_translate("MainWindow", "С"))
        self.label_9.setText(_translate("MainWindow", "Выберите дату"))
        self.label_3.setText(_translate("MainWindow", "Всего билетов"))
        self.label_2.setText(_translate("MainWindow", "Выберите площадку"))
        self.label_19.setText(_translate("MainWindow", "Время мероприятия"))
        self.label_17.setText(_translate("MainWindow", "Выберите тип площадки"))
        self.label_14.setText(_translate("MainWindow", "Выберите тип мероприятия"))
        self.label_11.setText(_translate("MainWindow", "С"))
        self.label_16.setText(_translate("MainWindow", "По"))
        self.label_4.setText(_translate("MainWindow", "Выберите таблицу"))
        self.eventSiteName.setPlaceholderText(_translate("MainWindow", "Название"))
        self.eventSiteType.setPlaceholderText(_translate("MainWindow", "Тип"))
        self.addEventSiteButton.setText(_translate("MainWindow", "Добавить"))
        self.addTool.setTabText(self.addTool.indexOf(self.tab1), _translate("MainWindow", "Добавить площадку"))
        self.addEventButton.setText(_translate("MainWindow", "Добавить"))
        self.label_13.setText(_translate("MainWindow", "Количество мест"))
        self.label_5.setText(_translate("MainWindow", "Выберите площадку"))
        self.label_8.setText(_translate("MainWindow", "Количество рядов"))
        self.eventName.setPlaceholderText(_translate("MainWindow", "Название"))
        self.eventType.setPlaceholderText(_translate("MainWindow", "Тип"))
        self.label_20.setText(_translate("MainWindow", "Дата"))
        self.label_21.setText(_translate("MainWindow", "Время"))
        self.addTool.setTabText(self.addTool.indexOf(self.tab2), _translate("MainWindow", "Добавить мероприятие"))

