# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 480)
        MainWindow.setMinimumSize(QtCore.QSize(825, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 451, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.eventSiteChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.eventSiteChoice.setObjectName("eventSiteChoice")
        self.gridLayout.addWidget(self.eventSiteChoice, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.placeChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.placeChoice.setObjectName("placeChoice")
        self.gridLayout.addWidget(self.placeChoice, 3, 2, 1, 1)
        self.eventChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.eventChoice.setObjectName("eventChoice")
        self.gridLayout.addWidget(self.eventChoice, 1, 1, 1, 2)
        self.rowChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.rowChoice.setObjectName("rowChoice")
        self.gridLayout.addWidget(self.rowChoice, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.addToOrderButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addToOrderButton.setFont(font)
        self.addToOrderButton.setObjectName("addToOrderButton")
        self.gridLayout.addWidget(self.addToOrderButton, 5, 1, 1, 2)
        self.ticketPrice = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ticketPrice.setFont(font)
        self.ticketPrice.setObjectName("ticketPrice")
        self.gridLayout.addWidget(self.ticketPrice, 4, 1, 1, 2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 300, 251, 148))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.firstName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName.setFont(font)
        self.firstName.setText("")
        self.firstName.setObjectName("firstName")
        self.verticalLayout.addWidget(self.firstName)
        self.lastName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName.setFont(font)
        self.lastName.setText("")
        self.lastName.setObjectName("lastName")
        self.verticalLayout.addWidget(self.lastName)
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 30, 271, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.ticketsList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ticketsList.setFont(font)
        self.ticketsList.setObjectName("ticketsList")
        self.verticalLayout_2.addWidget(self.ticketsList)
        self.payButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.payButton.setFont(font)
        self.payButton.setObjectName("payButton")
        self.verticalLayout_2.addWidget(self.payButton)
        self.formTicketsButton = QtWidgets.QPushButton(self.centralwidget)
        self.formTicketsButton.setGeometry(QtCore.QRect(310, 300, 491, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.formTicketsButton.setFont(font)
        self.formTicketsButton.setObjectName("formTicketsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forge Ticket Agency"))
        self.label_5.setText(_translate("MainWindow", "Место"))
        self.label_3.setText(_translate("MainWindow", "Выберите место"))
        self.label_2.setText(_translate("MainWindow", "Выберите площадку"))
        self.label.setText(_translate("MainWindow", "Выберите мероприятие"))
        self.label_7.setText(_translate("MainWindow", "Цена"))
        self.label_4.setText(_translate("MainWindow", "Ряд"))
        self.addToOrderButton.setText(_translate("MainWindow", "Добавить к заказу"))
        self.ticketPrice.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Данные о клиенте"))
        self.firstName.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.lastName.setPlaceholderText(_translate("MainWindow", "Фамилия"))
        self.email.setPlaceholderText(_translate("MainWindow", "E-mail (обязательно)"))
        self.label_8.setText(_translate("MainWindow", "Заказ"))
        self.payButton.setText(_translate("MainWindow", "Оплатить"))
        self.formTicketsButton.setText(_translate("MainWindow", "Сформировать билеты"))
