# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 641)
        MainWindow.setMinimumSize(QtCore.QSize(1155, 641))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 631, 410))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.ticketChooser = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.ticketChooser.setContentsMargins(0, 0, 0, 0)
        self.ticketChooser.setObjectName("ticketChooser")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ticketChooser.addWidget(self.label_10, 2, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ticketChooser.addWidget(self.label_3, 7, 0, 2, 1)
        self.placeChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.placeChoice.setObjectName("placeChoice")
        self.ticketChooser.addWidget(self.placeChoice, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.ticketChooser.addWidget(self.label_12, 2, 2, 1, 1)
        self.addToOrderButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addToOrderButton.setFont(font)
        self.addToOrderButton.setObjectName("addToOrderButton")
        self.ticketChooser.addWidget(self.addToOrderButton, 10, 1, 1, 2)
        self.rowChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.rowChoice.setObjectName("rowChoice")
        self.ticketChooser.addWidget(self.rowChoice, 8, 1, 1, 1)
        self.eventChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.eventChoice.setObjectName("eventChoice")
        self.ticketChooser.addWidget(self.eventChoice, 6, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.ticketChooser.addWidget(self.label_9, 0, 0, 2, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.ticketChooser.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.ticketChooser.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ticketChooser.addWidget(self.label_4, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ticketChooser.addWidget(self.label_11, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.ticketChooser.addWidget(self.label_13, 9, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.ticketChooser.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ticketChooser.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ticketChooser.addWidget(self.label, 6, 0, 1, 1)
        self.ticketPrice = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ticketPrice.setFont(font)
        self.ticketPrice.setObjectName("ticketPrice")
        self.ticketChooser.addWidget(self.ticketPrice, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ticketChooser.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ticketChooser.addWidget(self.label_5, 7, 2, 1, 1)
        self.eventSiteChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.eventSiteChoice.setObjectName("eventSiteChoice")
        self.ticketChooser.addWidget(self.eventSiteChoice, 4, 1, 1, 2)
        self.eventTypeChoice = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.eventTypeChoice.setObjectName("eventTypeChoice")
        self.ticketChooser.addWidget(self.eventTypeChoice, 5, 1, 1, 2)
        self.timeFrom = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.timeFrom.setKeyboardTracking(False)
        self.timeFrom.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeFrom.setCalendarPopup(False)
        self.timeFrom.setObjectName("timeFrom")
        self.ticketChooser.addWidget(self.timeFrom, 3, 1, 1, 1)
        self.timeTo = QtWidgets.QTimeEdit(self.gridLayoutWidget)
        self.timeTo.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeTo.setObjectName("timeTo")
        self.ticketChooser.addWidget(self.timeTo, 3, 2, 1, 1)
        self.dateFrom = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateFrom.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setCurrentSectionIndex(0)
        self.dateFrom.setObjectName("dateFrom")
        self.ticketChooser.addWidget(self.dateFrom, 1, 1, 1, 1)
        self.dateTo = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.ticketChooser.addWidget(self.dateTo, 1, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(700, 430, 431, 190))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.clientData = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.clientData.setContentsMargins(0, 0, 0, 0)
        self.clientData.setObjectName("clientData")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.clientData.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.firstName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName.setFont(font)
        self.firstName.setText("")
        self.firstName.setObjectName("firstName")
        self.clientData.addWidget(self.firstName)
        self.lastName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName.setFont(font)
        self.lastName.setText("")
        self.lastName.setObjectName("lastName")
        self.clientData.addWidget(self.lastName)
        self.email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.clientData.addWidget(self.email)
        self.clearData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clearData.setFont(font)
        self.clearData.setObjectName("clearData")
        self.clientData.addWidget(self.clearData)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(700, 30, 431, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.orderList = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.orderList.setContentsMargins(0, 0, 0, 0)
        self.orderList.setObjectName("orderList")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.orderList.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.ticketsList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ticketsList.setFont(font)
        self.ticketsList.setObjectName("ticketsList")
        self.orderList.addWidget(self.ticketsList)
        self.payButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.payButton.setFont(font)
        self.payButton.setObjectName("payButton")
        self.orderList.addWidget(self.payButton)
        self.cancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.orderList.addWidget(self.cancelButton)
        self.formTicketsButton = QtWidgets.QPushButton(self.centralwidget)
        self.formTicketsButton.setGeometry(QtCore.QRect(20, 470, 631, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.formTicketsButton.setFont(font)
        self.formTicketsButton.setObjectName("formTicketsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Билетное Агенство \"Кузница\""))
        self.label_10.setText(_translate("MainWindow", "Выберите время"))
        self.label_3.setText(_translate("MainWindow", "Выберите место"))
        self.label_12.setText(_translate("MainWindow", "По"))
        self.addToOrderButton.setText(_translate("MainWindow", "Добавить к заказу"))
        self.label_9.setText(_translate("MainWindow", "Выберите дату"))
        self.label_15.setText(_translate("MainWindow", "С"))
        self.label_16.setText(_translate("MainWindow", "По"))
        self.label_4.setText(_translate("MainWindow", "Ряд"))
        self.label_11.setText(_translate("MainWindow", "С"))
        self.label_13.setText(_translate("MainWindow", "руб."))
        self.label_14.setText(_translate("MainWindow", "Выберите тип мероприятия"))
        self.label_2.setText(_translate("MainWindow", "Выберите площадку"))
        self.label.setText(_translate("MainWindow", "Выберите мероприятие"))
        self.ticketPrice.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Цена"))
        self.label_5.setText(_translate("MainWindow", "Место"))
        self.label_6.setText(_translate("MainWindow", "Данные о клиенте"))
        self.firstName.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.lastName.setPlaceholderText(_translate("MainWindow", "Фамилия"))
        self.email.setPlaceholderText(_translate("MainWindow", "E-mail (обязательно)"))
        self.clearData.setText(_translate("MainWindow", "Очистить данные"))
        self.label_8.setText(_translate("MainWindow", "Заказ"))
        self.payButton.setText(_translate("MainWindow", "Оплатить заказ"))
        self.cancelButton.setText(_translate("MainWindow", "Отменить заказ"))
        self.formTicketsButton.setText(_translate("MainWindow", "Сформировать билеты"))
